---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: beer-import
spec:
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          containers:
            - image: "ghcr.io/bierteam/drinkn/beer-import:{{ .Chart.AppVersion }}"
              imagePullPolicy: Always
              name: beer-import
              envFrom:
                - secretRef:
                    name: drinkn-env
                    optional: false
  schedule: 0 9,22 * * *
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
