{{- if not .Values.pr.enabled }} # maybe mock a fake api to run against?
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: beer-import
spec:
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          securityContext:
            # runAsNonRoot: true #TODO
            seccompProfile:
              type: RuntimeDefault
          containers:
            - image: "ghcr.io/bierteam/drinkn/beer-import:{{ .Values.image.tag }}"
              imagePullPolicy: Always
              name: beer-import
              envFrom:
                - secretRef:
                    name: drinkn-env
                    optional: false
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - "ALL"
  schedule: 0 9,22 * * *
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
{{- end }}
