---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    sealedsecrets.bitnami.com/cluster-wide: "true"
    a8r.io/description: Expires on Sun, Jul 12 2026. https://github.com/settings/tokens?type=beta
  name: github-token
spec:
  encryptedData:
    token: AgBVVWZ6v4+RxxmGk111EXqkThffN0WF5K7sUlTcBtYMLlJBooIUMQcvieXOVvblpdYR3DSwhle8mR8Z5OmRREKAMS/7x7NEUvByYDcvbv6Np/9qFFTUKYQEKsTMeeWhrMVssJL52dfxINnbksKZ/PrNyKQW4zAugZ2uMPRPG6lxdmRQJ5FAA0yb7Bi6AhIcV7bSUgO76wvvd9JOMFYa42mP6RUzX8nLSXo+Uhz5awOwJIVyucCgXu7cPMyiaX8zZQrIkIjTqIQcBPuHSW1OlfgsD4u4sxB0oYYe8+0D2GyaC1ItcI0ydw4BpCcl4H2ilcTp5/M172QwoJH2F9FLLema07owahobt58rB7bTqkWHGNwerhfs9kvaUZ1cXorAKOixfw18CL8OkDYlXJ31SHNi5W5FFYA8DwJxriUcC6XNm3OSNe8aEVPsfscp+Bslud1Veuwj1Jg1R7z2NLsq5jqjkXgWhqpaQaljnrF+V9YD/zD6wvhDpkyqsMt9h7T3JkrQxAZ5/UUTd3NhvKopJ7hAfxv4FhVhZGeRDiGsN6hCP94demcfElj+5hImHAVwiYydbzf0Llotoh+6ZIVa31tWBgG091Y+Y13EVqoyJlaswHfWyB3/xv4MpsV7F0TTL0CVBFAlF+fcOz13ifd9OiirTU4SQWDMRE7yFY3OXnqHi/Ey9Q7LV2/PxDGCUJYgm4HElm8MPJbqtOW+mx3gMeA+wOHkYaHlYgTlnF/qJ6d5yVUQHnu8FtangrLKEOcJWeVxEBRPNjBAQxKsBUzMisduiDyfHt7LivvVAXMtDYXlQ3FZ6a0Q6SReahfBYH8=

# Maybe the start deployment and (still missing) stop deployment api calls are better handled with a sleep container woth lifecycle hooks
# https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/

{{- $ref := .Values.pr.ref }}
{{- $number := .Values.pr.number }}
{{- $fqdn := .Values.fqdn }}
{{- range .Values.pr.status }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ . | lower }}-hook
  annotations:
    argocd.argoproj.io/hook: {{ . }}
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: curl
          image: curlimages/curl
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-token
                  key: token
          command: ["ash", "-c"]
          args:
            - |
              API_URL="https://api.github.com/repos/bierteam/drinkn/dispatches"
              PAYLOAD='{
                "event_type": "{{ . }}",
                "client_payload": {
                  "ref": "{{ $ref }}",
                  "log_url": "https://argocd.lab.oscarr.nl/applications/argocd/drinkn-pr-{{ $number }}",
                  "environment_url": "https://{{ $fqdn }}"
                }
              }'
              # Use curl to send a POST request
              curl -L -i -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $GITHUB_TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                -d "$PAYLOAD" \
                "$API_URL"
      restartPolicy: Never
  backoffLimit: 0
{{- end }}
