# Maybe the start deployment and stop deployment api calls are better handled with a sleep container woth lifecycle hooks
# https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/

{{- $ref := .Values.pr.ref }}
{{- $number := .Values.pr.number }}
{{- $fqdn := .Values.fqdn }}
{{- range .Values.pr.status }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ . | lower }}-hook-{{ $number }}
  namespace: drinkn-hooks
  annotations:
    argocd.argoproj.io/hook: {{ . }}
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: curl
          image: curlimages/curl
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-token
                  key: token
          command: ["ash", "-c"]
          args:
            - |
              API_URL="https://api.github.com/repos/bierteam/drinkn/dispatches"
              PAYLOAD='{
                "event_type": "{{ . }}",
                "client_payload": {
                  "ref": "{{ $ref }}",
                  "log_url": "https://argocd.lab.oscarr.nl/applications/argocd/drinkn-pr-{{ $number }}",
                  "environment_url": "https://{{ $fqdn }}"
                }
              }'
              # Use curl to send a POST request
              curl -L -i -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $GITHUB_TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                -d "$PAYLOAD" \
                "$API_URL"
      restartPolicy: Never
  backoffLimit: 0
{{- end }}
