---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    sealedsecrets.bitnami.com/cluster-wide: "true"
    a8r.io/description: Expires on Wed, Aug 7 2024. https://github.com/settings/tokens?type=beta
  name: github-token
spec:
  encryptedData:
    token: AgASRow85Bv/IGZTftJ5BdtnqMejgyJMNiU7z5fwJkVYZFQoc5RTYchVK5a5y4tLpT256waDcOncWavGgTsXybNo5uPUukUNE21NsCiq/Po9RtG/NYmVmJ0VeNJSVES5JYB0MPU9SsKBli1mAUWQW7gP+cVeTZCyu5Ii9SGoKOxPRMNl+8U58WAy1pYfWNimU6WA2S83VXV9IUYOqGwKfiI4Jx7na0BihiZBbMnDWXIXM+aJQ4YJoZBJ0/TtsKABJK/ictxRSdzxjzDKNTgvTBX4Vh5Nx6lTkB2++5MHqjKF+/LnuL/KawVTZhJOVw7GRxr7AW6Wuyph3l2RENwBx27IKbrPZsdKWnmS4CswpwYh0jp0pnIrs8fgPGMu+/EPP+B+Xnvd3EkLsllXQBpXKFTswF5lzQPifj+oTwi6/6m91RgsnL9hCTHlt6tEuuwB6ge9CpiRpkc0Pqki/m0JhRjR+SNbv2XhlHaXRCMnzlnbc0cyVLwM73f6/UQ7A7eyIQ3EqFwuE1x76982gi9vFAMwqUWlgIlKBe9rt+mpvBXaawvkveCTnoaJ7VgncDnl/FlmDwFGmpX6locIBNvBL3xHSC5eKZ8t6ZyfhhkEXgDPw8GA8RHX9Sute6DAXrVux+lbQ4WphEcYWwPASx0KSLz2J2pxck6OdfQERQ0zekLWF/z1lBy6aMCgMMi24bEpIE2YKCuSHk33/oRQn32LRTIsiqnPsrQk071EMOVrcgPybFsjScFpOpx9YAN9ba58glBwuohXktAbdZ24ro3wZa1K1aqWZZ2/NqwSszg8PmZxX7mSRXFkqwHV3IRZpB4=

{{- $ref := .Values.pr.ref }}
{{- $number := .Values.pr.number }}
{{- $fqdn := .Values.fqdn }}
{{- range .Values.pr.status }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ . | lower }}-hook
  annotations:
    argocd.argoproj.io/hook: {{ . }}
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: curl
          image: curlimages/curl
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-token
                  key: token
          command: ["ash", "-c"]
          args:
            - |
              API_URL="https://api.github.com/repos/bierteam/drinkn/dispatches"
              PAYLOAD='{
                "event_type": "{{ . }}",
                "client_payload": {
                  "ref": "{{ $ref }}",
                  "log_url": "https://argocd.lab.oscarr.nl/applications/argocd/drinkn-pr-{{ $number }}",
                  "environment_url": "https://{{ $fqdn }}"
                }
              }'
              # Use curl to send a POST request
              curl -L -i -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $GITHUB_TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                -d "$PAYLOAD" \
                "$API_URL"
      restartPolicy: Never
  backoffLimit: 0
{{- end }}
