---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: drinkn
  annotations:
    link.argocd.argoproj.io/external-link: 'https://{{ .Values.fqdn }}'
spec:
  entryPoints:
    - websecure
  routes:
    {{- if not .Values.pr.enabled }}
    - match: Host(`drinkn.oscarr.nl`, `xn--xj8haa.tk`)
      kind: Rule
      services:
        - name: drinkn-frontend
          port: 80
    - match: Host(`drinkn.oscarr.nl`, `xn--xj8haa.tk`) && PathPrefix(`/api/v2/auth`)
      kind: Rule
      services:
        - name: drinkn-auth
          port: 80
    - match: Host(`drinkn.oscarr.nl`, `xn--xj8haa.tk`) && PathPrefix(`/api/v2/beer`)
      kind: Rule
      services:
        - name: drinkn-auth
          port: 80
    - match: Host(`drinkn.oscarr.nl`, `xn--xj8haa.tk`) && PathPrefix(`/api/v2/mix`)
      kind: Rule
      services:
        - name: drinkn-cocktail-api
          port: 80
    - match: Host(`drinkn.oscarr.nl`, `xn--xj8haa.tk`) && PathPrefix(`/api/v2/supermarket`)
      kind: Rule
      services:
        - name: drinkn-auth
          port: 80
    {{- end }}
    - match: Host(`{{ .Values.fqdn }}`)
      kind: Rule
      services:
        - name: pils-frontend
          port: 80
    - match: Host(`{{ .Values.fqdn }}`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: pils
          port: 80
