---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pils-frontend
  name: pils-frontend
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pils-frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pils-frontend
    spec:
      containers:
        - image: "ghcr.io/bierteam/drinkn/pils-frontend:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          name: pils-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: pils-frontend
spec:
  selector:
    app: pils-frontend
  ports:
    - port: 80
      name: default
      protocol: TCP
      targetPort: 80
