---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pils
  name: pils
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pils
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pils
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - image: ghcr.io/bierteam/drinkn/pils:{{ .Values.image.tag }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          envFrom:
            - secretRef:
                name: drinkn-env
                optional: false
          imagePullPolicy: Always
          name: pils
---
apiVersion: v1
kind: Service
metadata:
  name: pils
spec:
  selector:
    app: pils
  ports:
    - port: 80
      name: default
      protocol: TCP
      targetPort: 3000
