name: Main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
          - beer-import
          - pils
          - pils-frontend
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      -
        name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-${{ matrix.folder }}-${{ hashFiles('${{ matrix.folder }}/package-lock.json') }}
      -
        run: npm ci --force
        working-directory: ${{ matrix.folder }}
      -
        run: npm run build --if-present
        working-directory: ${{ matrix.folder }}
      -
        run: npm run test --if-present
        working-directory: ${{ matrix.folder }}
      -
        run: npm run lint --if-present
        working-directory: ${{ matrix.folder }}
      -
        uses: codecov/codecov-action@v3
        with:
          directory: ${{ matrix.folder }}
          
  # test-go:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       folder:
  #        - api
  #   steps:
  #     -
  #       uses: actions/checkout@v3
  #     -
  #       name: Set up Go
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: 1.20
  #     -
  #       name: Build
  #       run: go build ${{ matrix.folder }}
  #     -
  #       name: Test
  #       run: go test ${{ matrix.folder }}
  #     -
  #       uses: codecov/codecov-action@v3
  #       with:
  #         directory: ${{ matrix.folder }}

  docker:
    needs:
      - test-node
      # - test-go
    permissions:
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
          - beer-import
          - pils-frontend
          - pils
          # - api

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}/${{ matrix.folder }}
          tags: |
            type=ref,event=branch
            type=sha
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.folder }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha
          # https://docs.docker.com/build/building/cache/backends/#cache-mode

  deploy:
    if: ${{ github.event_name != 'pull_request' }}
    needs:
      - docker
    runs-on: ubuntu-latest
    environment: kubernetes
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy using Argo CD
        run: |
          # Access the commit SHA from GitHub context
          COMMIT_SHA="${{ github.sha }}"
          
          # Trim the first few characters to match the desired format (e.g., sha-c27d339)
          SHORT_SHA="sha-${COMMIT_SHA:0:7}"
          
          # Change image.tag in charts/drinkn/values.yaml
          sed -i "s|tag:.*|tag: \"$SHORT_SHA\"|" charts/drinkn/values.yaml

          # Commit and push the changes to the deploy branch
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add charts/drinkn/values.yaml
          git commit -m "Update image.tag to $SHORT_SHA"
          git push origin main
