name: Main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
          - beer-import-legacy
          - pils-legacy
          - frontend-legacy
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 1.20
      -
        name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-${{ matrix.folder }}-${{ hashFiles('${{ matrix.folder }}/package-lock.json') }}
      -
        run: npm ci
        working-directory: ${{ matrix.folder }}
      -
        run: npm run build --if-present
        working-directory: ${{ matrix.folder }}
      -
        run: npm run test --if-present
        working-directory: ${{ matrix.folder }}
      -
        run: npm run lint --if-present
        working-directory: ${{ matrix.folder }}
      -
        uses: codecov/codecov-action@v2
        with:
          directory: ${{ matrix.folder }}

  test-go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
         - beer-import
         - pils
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      -
        name: Build
        run: go build -v ./...
      -
        name: Test
        run: go test -v ./...

  docker:
    if: github.ref == 'refs/heads/master' || github.event == 'push'
    needs:
      - test-node
      - test-go
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
          - beer-import
          - beer-import-legacy
          - frontend
          - frontend-legacy
          - pils
          - pils-legacy

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}/${{ matrix.folder }}
          tags: |
            type=ref,event=branch
            type=sha
          flavor: |
            latest=true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          cache-from: type=registry,ref=${{ github.repository }}
          cache-to: type=registry,ref=${{ github.repository }}
          # https://docs.docker.com/build/building/cache/backends/#cache-mode
